1. 서울특별시 중에서 영등포로 줄인 이유가 무엇인가요?

2. 날씨와 주차차량의 대수는 어느 정도의 상관관계를 가지고 있나요?

3. 주변 영화관, 백화점, 공원과 같은 것이 주차 대수에 영향을 주었을 것인데 확인하셧나요?

In [5]:
import pandas as pd

df=pd.read_csv("../june/full1.csv")

In [6]:
df

,Unnamed: 0,park_name,capacity,park_phone,cur_parking,cur_parking_time,available_parking,count,date,hour,...,is_weekend,park_type_BP,park_type_BS,park_type_NP,park_type_NS,park_type_NW,que_status_20분,que_status_2시간,que_status_2일,available_parking_less_than_zero
0,2,현대성우아파트,228,02-3491-8954,228,2024-10-03 10:06:28,0,2,2024-10-03 01:07:33,10,...,False,False,True,False,False,False,True,False,False,105
1,6,이안테라디움방학역오피스텔,170,0,170,2024-10-03 10:06:28,0,6,2024-10-03 01:07:40,10,...,False,False,True,False,False,False,True,False,False,105
2,8,신한은행 방학동지점,24,0,26,2024-10-03 10:07:36,-2,8,2024-10-03 01:07:42,10,...,False,False,True,False,False,False,True,False,False,105
3,11,LG전자베스트샵 쌍문본점,29,0,29,2024-10-03 10:07:40,0,11,2024-10-03 01:07:45,10,...,False,False,True,False,False,False,True,False,False,105
4,13,정안빌딩,55,0,55,2024-10-03 10:07:41,0,13,2024-10-03 01:07:48,10,...,False,False,True,False,False,False,True,False,False,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,888,서강프라자,33,0,33,2024-10-03 10:25:47,0,891,2024-10-03 01:25:51,10,...,False,False,True,False,False,False,True,False,False,105
147,892,강남레체오피스텔,34,0,34,2024-10-03 10:25:44,0,895,2024-10-03 01:25:57,10,...,False,False,True,False,False,False,True,False,False,105
148,896,서초케이타운,87,0,87,2024-10-03 10:25:44,0,899,2024-10-03 01:26:01,10,...,False,False,True,False,False,False,True,False,False,105
149,897,내곡드림시티1,44,0,44,2024-10-03 10:25:39,0,900,2024-10-03 01:26:03,10,...,False,False,True,False,False,False,True,False,False,105
150,898,내곡프라임시티,38,0,38,2024-10-03 10:25:45,0,901,2024-10-03 01:26:04,10,...,False,False,True,False,False,False,True,False,False,105